spring.datasource.url=jdbc:postgresql://localhost:5432/iisdb
spring.datasource.username=iisuser
spring.datasource.password=iispassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
grpc.server.port=9090

cxf.path=/ws


jwt.secret=4f512e011fe0ef04f6f3fa08528ca3e81e8c8ce128ae2337e186df4cc85a5ec9e5c9caad1b9d076bcedc5b6c5a7e90247495c6d7a0bbfca5b7cf39dae5c2a2a3


app.use-public-api=false
app.zendesk.base-url=https://algebra-59529.zendesk.com/api/v2
app.zendesk.email=alovric@algebra.hr/token
app.zendesk.token=nwwW4qbtqwcjmymxVb3Lo17zmG3l4ues3WONuvU3

spring.graphql.graphiql.enabled=true